create table if not exists public.language_preferences (
  visitor_id uuid primary key,
  language text not null check (language in ('en', 'tr')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.language_preferences enable row level security;

drop policy if exists "language preferences are countable" on public.language_preferences;
drop policy if exists "language preferences can be inserted" on public.language_preferences;
drop policy if exists "language preferences can be updated" on public.language_preferences;

create policy "language preferences are countable"
  on public.language_preferences
  for select
  using (true);

create policy "language preferences can be inserted"
  on public.language_preferences
  for insert
  with check (language in ('en', 'tr'));

create policy "language preferences can be updated"
  on public.language_preferences
  for update
  using (true)
  with check (language in ('en', 'tr'));

create table if not exists public.visitor_events (
  id bigint generated by default as identity primary key,
  visitor_id uuid not null,
  event_type text not null check (event_type in ('page_view', 'email_click')),
  path text not null default '/',
  created_at timestamptz not null default now()
);

create index if not exists visitor_events_event_type_created_at_idx
  on public.visitor_events (event_type, created_at desc);

create index if not exists visitor_events_visitor_id_idx
  on public.visitor_events (visitor_id);

alter table public.visitor_events enable row level security;

drop policy if exists "visitor events are countable" on public.visitor_events;
drop policy if exists "visitor events can be inserted" on public.visitor_events;

create policy "visitor events are countable"
  on public.visitor_events
  for select
  using (true);

create policy "visitor events can be inserted"
  on public.visitor_events
  for insert
  with check (event_type in ('page_view', 'email_click'));

create table if not exists public.visitor_profiles (
  visitor_id uuid primary key,
  first_seen timestamptz not null default now(),
  last_seen timestamptz not null default now()
);

create index if not exists visitor_profiles_last_seen_idx
  on public.visitor_profiles (last_seen desc);

alter table public.visitor_profiles enable row level security;

drop policy if exists "visitor profiles are countable" on public.visitor_profiles;
drop policy if exists "visitor profiles can be inserted" on public.visitor_profiles;
drop policy if exists "visitor profiles can be updated" on public.visitor_profiles;

create policy "visitor profiles are countable"
  on public.visitor_profiles
  for select
  using (true);

create policy "visitor profiles can be inserted"
  on public.visitor_profiles
  for insert
  with check (true);

create policy "visitor profiles can be updated"
  on public.visitor_profiles
  for update
  using (true)
  with check (true);
